// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildDeletePlan(arg1:string):Promise<main.DeletePlanResult>;

export function RunReadOnlyScan():Promise<main.ScanResult>;
