// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RunReadOnlyScan(arg1:main.ScanRequest):Promise<main.ScanResult>;
