// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDeletePlan(arg1) {
  return window['go']['main']['App']['BuildDeletePlan'](arg1);
}

export function RunReadOnlyScan() {
  return window['go']['main']['App']['RunReadOnlyScan']();
}
